"""Add categories table.

Revision ID: 4172bf5732b7
Revises: 0691aa726c04
Create Date: 2023-11-27 13:48:48.206993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4172bf5732b7'
down_revision = '0691aa726c04'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    from sqlalchemy import text
    from sqlalchemy.orm.session import Session
    session = Session(bind=op.get_bind())
    smt = text('PRAGMA foreign_keys = ON;')
    session.execute(smt)
    session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('сategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("category", 'сategories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('сategories')
    # ### end Alembic commands ###
