"""Add two fields aboutMe, lastSeen for User

Revision ID: a79bf5312999
Revises: aa9a7b7cdbda
Create Date: 2023-11-10 16:56:52.459955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79bf5312999'
down_revision = 'aa9a7b7cdbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aboutMe', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('lastSeen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastSeen')
        batch_op.drop_column('aboutMe')

    # ### end Alembic commands ###
